### PR TITLE
reliability against dropped packets

### PR DESCRIPTION
**Pull request by dominictarr**
Edit: use randomized testing to detect cases where dropped packets breaks things, then use timers to fix that.

I did try an idea to attach a message "seq" that you could use to check if a message had been responded to, but later found it simpler to just use a timer to check if the desired thing has happened yet (such as connecting to some peers), and if not, try again.

### CODE REVIEW

**Comment by heapwolf** [comment]
> to detect dropped packets, include a `seq` (couldn't think of a better name, but 'token' or "cookie' would also fit)
> 
> any message that is a response to automatic response to another message copies the `seq` property.
> 
> ```
> send({type: 'ping', seq: 123,...}) ------>
> recv <-- {type: 'pong', seq: 123,...}
> ```
> 
> etc. for every message type. that means a join, triggers connects, or an "error", are both tracable back to that join. If there havn't been any messages with the expected seq, a packet may have been dropped, so retry.
> 
> this PR isn't finished yet, there will be timeouts and retries, and test coverage

+1 for token, sequence implies a sequential value, but seq is random

**Comment by dominictarr** [comment]
found several other places that packet drops were causing failures... but fixed them just using timers. maybe don't even need seq/token?

**Comment by heapwolf** [comment]
> found several other places that packet drops were causing failures... but fixed them just using timers. maybe don't even need seq/token?

Nice. Yeah, ideally we would avoid introducing a new concept

**Comment by dominictarr** [comment]
making progress here, I think the problem is with join messages now. I think I'll add the ability to run tests that only drop particular types of messages. Maybe because of packet lengths something like that might happen with real packets but really it's just so that I can reason about test failures. If I know one sort of packet isn't being dropped in that test, then I know that's not the problem!

**Comment by dominictarr** [comment]
okay going back to a simpler way to rely on join messages, just check how many peers are in the swarm, and reconnect if it's too low. currently also passing the number of peers... but it's not working. you might think that there just aren't enough peers. maybe the answer is joining, but just with incremental backoff out to keepalive time

**Comment by dominictarr** [comment]
Okay, now I've got it rejoining at the keepalive, which passes the drop message test, but one other test is going into an infinite loop...

**Comment by dominictarr** [comment]
@heapwolf this is all passing and ready for merge

**Pull request merged**
